'use client'


import { ChakraProvider } from "@chakra-ui/react"
import Header from "./Components/Header"


export const metadata = {
  title: 'PIAIC',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ChakraProvider>
        <Header />
        {children}
        </ChakraProvider>
        </body>
    </html>
  )
}
